# Generated by Django 3.2.23 on 2023-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20231112_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
