# Generated by Django 3.2.23 on 2023-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
